name: dart_auth_ex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_auth_cognito: ^1.0.0-0
  amplify_authenticator: ^1.0.0-0
  amplify_flutter: ^1.0.0-0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true