name: dart_auth_ex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/auth/amplify_auth_cognito
  amplify_authenticator:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify_authenticator
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify/amplify_flutter
  flutter:
    sdk: flutter

dependency_overrides:
  amplify_core:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify_core
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify/amplify_flutter
  amplify_flutter_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify/amplify_flutter_ios
  amplify_flutter_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/amplify/amplify_flutter_android
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/auth/amplify_auth_cognito
  amplify_auth_cognito_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/auth/amplify_auth_cognito_ios
  amplify_auth_cognito_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/auth/amplify_auth_cognito_dart
  amplify_secure_storage:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/secure_storage/amplify_secure_storage_dart
  aws_common:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/aws_common
  aws_signature_v4:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/aws_signature_v4
  worker_bee:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: next
      path: packages/worker_bee/worker_bee

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true